Updated the command for GKE cluster creation in standard mode
GoogleCloudPlatform/bank-of-anthos pull request #535
Opened 2021-12-07 18:00 UTC by Harsha6174

Fixes # .

Change summary:
Updated the GKE standard cluster creation command to include the ones for monitoring and logging. 

Remaining issues / concerns:

2021-12-09 19:52 UTC, Shabirmean commented on v1.35.0
> +
Remove this additional file!

2021-12-09 19:52 UTC, Shabirmean requested changes
Thank you for the changes. There is a minor request for change!

2021-12-10 04:54 UTC, Harsha6174 commented
Thanks, @Shabirmean . I have removed the extra file (v1.35.0) that had cropped in.

2021-12-10 19:49 UTC, Shabirmean approved these changes
LGTM! Thank you for helping us keep the sample up to date

2021-12-10 19:49 UTC, merged